apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fdv86u8bg-go
  janus-idp.io/tekton: fdv86u8bg-go
  backstage.io/kubernetes-id: fdv86u8bg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdv86u8bg-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
