apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fdv86u8bg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fdv86u8bg-go 
  name: fdv86u8bg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fdv86u8bg-go 
